### ISSUE TITLE
No late fusion in source code

### ISSUE THREAD

**Issue by nsa05605** [Toytiny/RadarNet-pytorch#2]
Hi,
I'm looking for your source code now, and I found something weird..

there are late_fusion module in utils.py, but it does not use in operation. like in main.py.
So, can you share your latest source code contain late_fusion?

Thank you.

**Comment by Toytiny** [comment]
The uploaded one is already the latest code that I produce three years ago. You could modify and add code yourself to align better with the orginal paper.
